name: Build project on push

# Controls when the action will run. Triggers the workflow on push or pull request
on:
  workflow_dispatch:
  push:
    # Sequence of patterns matched against refs/tags
        
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: resolutiongmbh/atlassian-plugin-sdk-with-node

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Build front
        working-directory: js
        run: |
              yarn install
              yarn build-prod
              
      - name: Build atlas package
        run: atlas-package
        
      - name: Upload action artifacts
        uses: actions/upload-artifact@master
        with:
          name: package artifacts
          path: | 
              target/*.jar
