name: Release on version tag push

# Controls when the action will run. Triggers the workflow on push or pull request

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'groovy-[0-9]+.[0-9]+*' # Push events to matching v*, i.e. 1.0, 20.15.10
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'     
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "release"
  release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: resolutiongmbh/atlassian-plugin-sdk-with-node

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Select release version from tag or input (if runx manually)

      - run: echo '::set-env name=VERSION::${{ github.ref }}'
        
      - run: echo '::set-env name=VERSION::${{ github.event.inputs.version }}'
        if: ${{ github.event.inputs.version }}

      - name: Build front
        working-directory: js
        run: |
              yarn install
              yarn build-prod
              
      - name: Run atlas-integration-test
        run: atlas-integration-test

      - name: Build atlas package
        run: atlas-package -P production
        
      - name: Upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: package artifacts
          path: | 
              target/*.jar
          
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ env.VERSION }}
          release_name: Release ${{ env.VERSION }}
          # body: changelog
          draft: false
          prerelease: false
          
      - name: Upload jar binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/*.jar
          tag: ${{ env.VERSION }}
          overwrite: true
          file_glob: true
